Models/CustomerService.cs
using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class CustomerService
    {

        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }
    }
}

Models/CustomerServiceDt.cs

using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class CustomerServiceDt
    {


        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace EmmascoTravelsApp1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LoginService.cs
using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class LoginService
    {

        public int Id { get; set; }

        [Required]

        [MaxLength(50)]

        public string UserName { get; set; }

        [Required]

        [MaxLength(30)]
        public string Password { get; set; }

        
    }
}

Models/LoginServiceDt.cs
using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class LoginServiceDt
    {

        [Required]
        [MaxLength(50)]
        public string UserName { get; set; }


        public string Password { get; set; }

    }
}


Models/RegisterService.cs
using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class RegisterService
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string Password { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }


    }
}

Models/RegisterServiceDt.cs
using System.ComponentModel.DataAnnotations;

namespace EmmascoTravelsApp1.Models
{
    public class RegisterServiceDt
    {

        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string Password { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }


    }
}


Controllers/CustomerController.cs
using EmmascoTravelsApp1.Data;
using EmmascoTravelsApp1.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmmascoTravelsApp1.Controllers
{
    public class CustomerController : Controller
    {


        private readonly AppDbContext context;
        private readonly IWebHostEnvironment environment;

        public CustomerController (AppDbContext context, IWebHostEnvironment environment)
        {
            this.context = context;
            this.environment = environment;
        }
        public IActionResult Index()
        {

            var customer = context.CustomerServices.ToList();

            return View(customer);
        }


        public IActionResult Create()
        {
            return View();
        }

            [HttpPost]
            public IActionResult Create(CustomerServiceDt customerServiceDt)
            {
                if (!ModelState.IsValid)
                {
                    return View(customerServiceDt);
                }

                // Save data to database
                CustomerService customerService = new CustomerService()
                {
                    FirstName = customerServiceDt.FirstName,
                    LastName = customerServiceDt.LastName,
                    Email = customerServiceDt.Email,
                    Phone = customerServiceDt.Phone,
                    Address = customerServiceDt.Address
                };

                context.CustomerServices.Add(customerService);
                context.SaveChanges();

                return RedirectToAction("Index", "Customer");
            }

        }
        
        }

   



Controllers/HomeController.cs
using System.Diagnostics;
using EmmascoTravelsApp1.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmmascoTravelsApp1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginServiceController.cs
using EmmascoTravelsApp1.Data;
using Microsoft.AspNetCore.Mvc;

namespace EmmascoTravelsApp1.Controllers
{
    public class LoginServiceController : Controller
    {

        private readonly AppDbContext context;

        public LoginServiceController(AppDbContext context) {

            this.context = context;
        }


        public IActionResult Index()
        {

            var login = context.LoginServices.ToList();

            return View(login);
        }

        //Add details to Db


        public IActionResult Create()
        {
            return View();
        }
    }
}

Controllers/RegisterServiceController.cs
using EmmascoTravelsApp1.Data;
using Microsoft.AspNetCore.Mvc;

namespace EmmascoTravelsApp1.Controllers
{
    public class RegisterServiceController : Controller
    {

        private readonly AppDbContext context;

        public RegisterServiceController(AppDbContext context)
        {

            this.context = context;
        }


        public IActionResult Index()
        {

            var register = context.RegisterServices.ToList();

            return View(register);
        }

        //Add details to Db


        public IActionResult Create()
        {
            return View();
        }
    }
}


Views/Customer/Create.cshtml


@model CustomerServiceDt

<div class="card">
    <div class="card-header">
        Fill To Continue
    </div>
    <div class="card-body">
        <h5 class="card-title">Customer</h5>

        <form method="post">
            <div class="row mb-3">
                <label asp-for="FirstName" class="col-sm-2 col-form-label">First Name</label>
                <div class="col-sm-10">
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label asp-for="LastName" class="col-sm-2 col-form-label">Last Name</label>
                <div class="col-sm-10">
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label asp-for="Email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label asp-for="Phone" class="col-sm-2 col-form-label">Phone</label>
                <div class="col-sm-10">
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label asp-for="Address" class="col-sm-2 col-form-label">Address</label>
                <div class="col-sm-10">
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-5">
                <label for="sub" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">SUBMIT</button>
                    <a asp-action="Index" class="btn btn-danger">CANCEL</a>
                </div>
            </div>
        </form>
    </div>
</div>


Views/Customer/Index.cshtml
@model List<CustomerService>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<a class="btn btn-primary" asp-controller="Customer" asp-action="Create">Add Details</a>

@foreach (var customer in Model)
{
    <ul class="list-group">
        <li class="list-group-item list-group-item-primary">Customer ID: @customer.Id</li>
        <li class="list-group-item">First Name: @customer.FirstName</li>
        <li class="list-group-item list-group-item-secondary">Last Name: @customer.LastName</li>
        <li class="list-group-item list-group-item-success">Email: @customer.Email</li>
        <li class="list-group-item list-group-item-info">Phone: @customer.Phone</li>
        <li class="list-group-item list-group-item-dark">Address: @customer.Address</li>
        <li class="list-group-item">
            <a class="btn btn-primary" asp-controller="Customer" asp-action="Edit" asp-route-id="@customer.Id">Edit</a>
            <a class="btn btn-danger" asp-controller="Customer" asp-action="Delete" asp-route-id="@customer.Id">Delete</a>
        </li>
    </ul>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Emmasco Travels</h1>
    <p> <a href="#">
    <img src="image1/build1.jpg" width="400" height="450" alt="Home picture"/>




    </a>    
    </p>
</div>

<section class="course">
    <div class="fine" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="400">
        <h1>TRAVEL WITH EMMASCO TEAM</h1>
        <h2>Services we provide</h2>
    </div>
    <div class="row">
        <div class="courseCol" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="400">
            <h3>Packages</h3><br>
            <img src="images/suitcase.png">
            <p>Our travel packages offer flexible travel packages, expert guidance, and seamless experiences, ensuring your journey is stress-free and unforgettable, with options tailored to fit every interest and budget.</p>
        </div>


        <div class="courseCol" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="400">
            <h3>Flights</h3><br>
            <img src="images/plane.png">
            <p>Book your flights with us for convenient, affordable, and hassle-free travel to destinations worldwide, with versatile options to suit your schedule and preferences, ensuring a journey from departure to arrival.</p>
        </div>


        <div class="courseCol" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="400">
            <h3>Airline Ticketing</h3><br>
            <img src="images/airline-ticket.png">
            <p>Get your airline tickets booked with us for a hassle-free experience, with options to suit your schedule and budget, ensuring convenient travel to your desired destination, with flexibility and affordability.</p>
        </div>
    </div>
    <a href="services.html"><button>Read more</button></a>
</section>

Views/LoginService/Create.cshtml
@model LoginServiceDt;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="card">
    <div class="card-header">
        Login To Continue
    </div>
    <div class="card-body">
        <h5 class="card-title">Login</h5>

        <form method="post">
            <div class="row mb-3">
                <label for="userName" class="col-sm-2 col-form-label">User Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="userName" />
                </div>
            </div>

            <div class="row mb-3">
                <label for="userPassword" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="userPassword" />
                </div>
            </div>

            <div class="row mb-5">
                <label for="sub" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-8">

                    <button type="submit" class="btn btn-primary" asp-controller="LoginService" asp-action="Create">SUBMIT</button>
                </div>
            </div>

        </form>
    </div>
</div>





Views/LoginService/Index.cshtml
@model List<LoginService>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<a class="btn btn-primary" asp-controller="LoginService" asp-action="Create">Login Here</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>UserName</th>
            <th>Password</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var login in Model)
        {
            <tr>
                <td>@login.Id</td>
                <td>@login.UserName</td>
                <td>@login.Password</td>

                <td>
                    <a class="btn btn-primary" asp-controller="LoginService" asp-action="Edit" asp-route-id="@login.Id">Edit</a>
                    <a class="btn btn-danger" asp-controller="LoginService" asp-action="Delete" asp-route-id="@login.Id">Delete</a>
                </td>


            </tr>
        }
    </tbody>
</table>



Views/RegisterService/Create.cshtml
@model RegisterServiceDt;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="card">
    <div class="card-header">
        Register To Continue
    </div>
    <div class="card-body">
        <h5 class="card-title">Register</h5>

        <form method="post">



            <div class="row mb-3">
                <label for="firstName" class="col-sm-2 col-form-label">First Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form asp-for="FirstName" class="form-control" id="firstName" name="FirstName" />
                </div>
            </div>

            <div class="row mb-3">
                <label for="lastName" class="col-sm-2 col-form-label">Last Name</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="LastName" class="form-control" id="lastName" name="LastName" />
                </div>
            </div>

            <div class="row mb-3">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="Email" class="form-control" id="email" name="Email" />
                </div>
            </div>

            <div class="row mb-3">
                <label for="phone" class="col-sm-2 col-form-label">Phone</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="Phone" class="form-control" id="phone" name="Phone" />
                </div>
            </div>

            <div class="row mb-3">
                <label for="address" class="col-sm-2 col-form-label">Address</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="Address" class="form-control" id="address" name="Address" />
                </div>
            </div>

            <div class="row mb-5">
                <label for="carImage" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-8">

                    <button type="submit" class="btn btn-primary" asp-controller="RegisterService" asp-action="Create">SUBMIT</button>
                </div>
            </div>
        </form>
    </div>
</div>


Views/RegisterService/Index.cshtml


@model List<RegisterService>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<a class="btn btn-primary" asp-controller="RegisterService" asp-action="Create">Reister Here</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Phone</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var register in Model)
        {
            <tr>
                <td>@register.Id</td>
                <td>@register.FirstName</td>
                <td>@register.LastName</td>
                <td>@register.Email</td>
                <td>@register.Password</td>
                <td>@register.Phone</td>
                <td>@register.Address</td>

                <td>
                    <a class="btn btn-primary" asp-controller="RegisterService" asp-action="Edit" asp-route-id="@register.Id">Edit</a>
                    <a class="btn btn-danger" asp-controller="RegisterService" asp-action="Delete" asp-route-id="@register.Id">Delete</a>
                </td>


            </tr>
        }
    </tbody>
</table>




Views/Shared/_Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EmmascoTravelsApp1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmmascoTravelsApp1.styles.css" asp-append-version="true"/>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">EmmascoTravels</a>
                <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                    </ul>
                    <ul class="navbar-nav ms-auto me-5">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="RegisterService" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LoginService" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EmmascoTravelsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>



Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EmmascoTravelsApp1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmmascoTravelsApp1.styles.css" asp-append-version="true"/>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">EmmascoTravels</a>
                <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                    </ul>
                    <ul class="navbar-nav ms-auto me-5">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="RegisterService" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LoginService" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EmmascoTravelsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

